# Generated by Django 2.2.3 on 2019-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_app', '0003_stuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_age', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('stu_num', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('college', models.CharField(max_length=64)),
                ('class_num', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('depart', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('stu_id', models.CharField(max_length=64)),
                ('nation', models.CharField(max_length=10)),
                ('stu_addr', models.CharField(max_length=64)),
                ('others', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
